name: ubuntu minimal meson build

on:
    push:
        branches: ["main", "devel-github-action"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: install dependencies
              run : |
                sudo apt-get update
                sudo apt-get install -y meson python3-cogapp zlib1g-dev libbz2-dev libzma5 libcunit1-ncurses-dev
            - name: hello world
              run: echo hello world!
