name: ubuntu minimal meson build

on:
    push:
        branches: ["main", "devel-github-action"]

jobs:
    build_linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: install dependencies
              run : |
                sudo apt-get update
                sudo apt-get install -y meson python3-cogapp zlib1g-dev libbz2-dev liblzma-dev libcunit1-ncurses-dev

            - name: meson config build dir
              run: meson setup build/

            - name: meson compile
              run: meson compile -C build/

            - name: create release draft
              uses: softprops/action-gh-release@v1
              with:
                  draft: true
                  files: |
                    build/src/qman

    build_macos:
        runs-on: macos-15
        steps:
            - uses: actions/checkout@v4
            - uses: Homebrew/actions/setup-homebrew@main

            - name: install dependencies
              run: brew install meson cogapp ncurses zlib bzip2 xz cunit

            - name: meson config build dir
              run: meson setup build/ -Dpkg_config_path=/usr/local/opt/ncurses/lib/pkgconfig

            - name: meson compile
              run: meson compile -C build/
