name: ubuntu minimal meson build

on:
    push:
        branches: ["main", "devel-github-action"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: install dependencies
              run : |
                sudo apt-get update
                sudo apt-get install -y meson python3-cogapp zlib1g-dev libbz2-dev xz-utils libcunit1-ncurses-dev
            - name: meson config build dir
              run: meson setup build/
            - name: meson compile
              run: meson compile -C build/
            - name: hello world
              run: echo hello world!
